alias tf=terraform
tfp() {
    terraform plan $* -var-file="$(terraform workspace show).tfvars"
}
tfa() {
    terraform apply $* -var-file="$(terraform workspace show).tfvars"
}
# tfa() {
#     if [ -f ".$(terraform workspace show).protected" ]; then
#         echo "TERRAFORM OPERATION FORBIDDEN"
#     else
#         terraform apply $* -var-file="$(terraform workspace show).tfvars"
#     fi
# }
tfaa() {
    tfa -auto-approve $*
}
tfd() {
    tfa -destroy $*
}
tfda() {
    tfa -destroy -auto-approve $*
}
